# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GO_VERSION: '1.21.0'

jobs:
  lint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - ccwc
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: false
    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        working-directory: ${{ matrix.app }}

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - ccwc
    defaults:
      run:
        working-directory: ./${{ matrix.app }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Unit Test
      run: make test
